name: lightgan-ld
channels: [pytorch, nvidia, conda-forge, defaults]
dependencies:
  - python=3.10
  - pytorch>=2.1
  - torchvision
  - pytorch-cuda=12.2
  - numpy
  - h5py
  - pyyaml
  - tqdm
  - pillow
  - matplotlib
  - pandas
  - scipy
  - scikit-image
  - tensorboard
  - pip
  - pip:
      - lpips>=0.1.4
      - wandb>=0.16
      - thop>=0.1.1
      - pytest>=7
